// Generated by gencpp from file servant/WorkGoal.msg
// DO NOT EDIT!


#ifndef SERVANT_MESSAGE_WORKGOAL_H
#define SERVANT_MESSAGE_WORKGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace servant
{
template <class ContainerAllocator>
struct WorkGoal_
{
  typedef WorkGoal_<ContainerAllocator> Type;

  WorkGoal_()
    : task_name()
    , difficulty(0)  {
    }
  WorkGoal_(const ContainerAllocator& _alloc)
    : task_name(_alloc)
    , difficulty(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _task_name_type;
  _task_name_type task_name;

   typedef int32_t _difficulty_type;
  _difficulty_type difficulty;




  typedef boost::shared_ptr< ::servant::WorkGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::servant::WorkGoal_<ContainerAllocator> const> ConstPtr;

}; // struct WorkGoal_

typedef ::servant::WorkGoal_<std::allocator<void> > WorkGoal;

typedef boost::shared_ptr< ::servant::WorkGoal > WorkGoalPtr;
typedef boost::shared_ptr< ::servant::WorkGoal const> WorkGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::servant::WorkGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::servant::WorkGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace servant

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'servant': ['/home/jelen/code/jelen/ros/ros-playground/02/devel/share/servant/msg'], 'actionlib_msgs': ['/opt/ros/lunar/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::servant::WorkGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servant::WorkGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servant::WorkGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servant::WorkGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servant::WorkGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servant::WorkGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::servant::WorkGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ba6e9bcf0af82e72e9356429c403f0c";
  }

  static const char* value(const ::servant::WorkGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ba6e9bcf0af82e7ULL;
  static const uint64_t static_value2 = 0x2e9356429c403f0cULL;
};

template<class ContainerAllocator>
struct DataType< ::servant::WorkGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servant/WorkGoal";
  }

  static const char* value(const ::servant::WorkGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::servant::WorkGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
string task_name\n\
int32 difficulty\n\
";
  }

  static const char* value(const ::servant::WorkGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::servant::WorkGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_name);
      stream.next(m.difficulty);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WorkGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::servant::WorkGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::servant::WorkGoal_<ContainerAllocator>& v)
  {
    s << indent << "task_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.task_name);
    s << indent << "difficulty: ";
    Printer<int32_t>::stream(s, indent + "  ", v.difficulty);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVANT_MESSAGE_WORKGOAL_H
