; Auto-generated. Do not edit!


(cl:in-package servant-msg)


;//! \htmlinclude WorkGoal.msg.html

(cl:defclass <WorkGoal> (roslisp-msg-protocol:ros-message)
  ((task_name
    :reader task_name
    :initarg :task_name
    :type cl:string
    :initform "")
   (difficulty
    :reader difficulty
    :initarg :difficulty
    :type cl:integer
    :initform 0))
)

(cl:defclass WorkGoal (<WorkGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <WorkGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'WorkGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name servant-msg:<WorkGoal> is deprecated: use servant-msg:WorkGoal instead.")))

(cl:ensure-generic-function 'task_name-val :lambda-list '(m))
(cl:defmethod task_name-val ((m <WorkGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader servant-msg:task_name-val is deprecated.  Use servant-msg:task_name instead.")
  (task_name m))

(cl:ensure-generic-function 'difficulty-val :lambda-list '(m))
(cl:defmethod difficulty-val ((m <WorkGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader servant-msg:difficulty-val is deprecated.  Use servant-msg:difficulty instead.")
  (difficulty m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <WorkGoal>) ostream)
  "Serializes a message object of type '<WorkGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'task_name))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'task_name))
  (cl:let* ((signed (cl:slot-value msg 'difficulty)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <WorkGoal>) istream)
  "Deserializes a message object of type '<WorkGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'task_name) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'task_name) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'difficulty) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<WorkGoal>)))
  "Returns string type for a message object of type '<WorkGoal>"
  "servant/WorkGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'WorkGoal)))
  "Returns string type for a message object of type 'WorkGoal"
  "servant/WorkGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<WorkGoal>)))
  "Returns md5sum for a message object of type '<WorkGoal>"
  "5ba6e9bcf0af82e72e9356429c403f0c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'WorkGoal)))
  "Returns md5sum for a message object of type 'WorkGoal"
  "5ba6e9bcf0af82e72e9356429c403f0c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<WorkGoal>)))
  "Returns full string definition for message of type '<WorkGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string task_name~%int32 difficulty~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'WorkGoal)))
  "Returns full string definition for message of type 'WorkGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string task_name~%int32 difficulty~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <WorkGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'task_name))
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <WorkGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'WorkGoal
    (cl:cons ':task_name (task_name msg))
    (cl:cons ':difficulty (difficulty msg))
))
